name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: sol
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/solhann
            git pull
            /usr/local/bin/sass styles.scss styles.css
            /usr/local/bin/sass blursed.scss blursed.css
            /usr/local/bin/sass login.scss login.css
            /usr/local/bin/sass search.scss search.css
            /usr/local/bin/sass search-result.scss search-result.css

